#This Message is sent to the player when they execute /spawn
spawn-arrival: "&8[&9SetSpawn&8] &2Welcome to Spawn!"

#This Message is sent to the player when they execute /spawn but there is no spawn-point set
no-spawn-point: "&8[&9SetSpawn&8] &4You have not set a spawn-point. Use /spawn-point to set it!"

#This Message is sent to the player when they execute /spawn-point
spawn-set: "&0[&9SetSpawn&0] &2You have set the spawn-point!"

#This Message is sent to the player when they execute /spawn-point, but they don't have permission
no-permission: "&0[&9SetSpawn&0] &4You don't have permission to use this command!"

#The message sent to the player if they are on cooldown
#DO NOT ADD ANYTHING AFTER THE WORD ANOTHER OTHERWISE IT WILL NOT WOR PROPERLY!!! You can still change the last word and anything before it
cooldown-message: "&0[&9SetSpawn&0] &4Sorry, you can't use this command for another"

#How long to wait until you can use the command again (in seconds)
cooldown-time: 10

#Click this link to see the color codes you can use here. https://www.digminecraft.com/lists/color_list_pc.php
#instead of 'ยง' use '&'
